# demo file for server config

# Network Settings 
PORT = 3000
MAX_CONNECTIONS = 30
TIMEOUT = 15

# Security Settings
SSL_ENABLED = true
SSL_CERT = /path/certificate.pem

# Loggins Settings
LOG_LEVEL = INFO
LOG_FILE = /path/demo.log

# Others Settings 
AUTO_AIM= DISABLE
ONSPEED = ENABLE